name: CI checks

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17
    - name: Detekt
      run: make detekt
    - name: Test Common
      run: make testCommon
    - name: Build Android
      run: make buildAndroid
